In [ ]:
#KNN

In [9]:
from sklearn.datasets import fetch_openml 
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False) 
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [10]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
silhouette_scores = []
kmeans_10 = None

for i in range(8,13):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit_predict(X)
    if i == 10:
        kmeans_10 = kmeans
    silhouette_scores.append(silhouette_score(X, kmeans.labels_))

In [11]:
print(silhouette_scores)

[0.07338401965925966, 0.05683381826333592, 0.05869201052848778, 0.05836351154790604, 0.05894738457992754]


In [12]:
import pickle as pkl
fileObject = open("kmeans_sil.pkl", 'wb')
pkl.dump(silhouette_scores, fileObject)
fileObject.close()

In [32]:
from sklearn.metrics import confusion_matrix
conMatrix = confusion_matrix(y, kmeans_10.predict(X))
theBiggest = set()
for row in conMatrix:
    print(np.argmax(row))
    theBiggest.add(np.argmax(row))
theBiggest = list(theBiggest)
theBiggest.sort()
print(theBiggest)
print(conMatrix)

9
1
4
0
3
0
6
5
8
3
[0, 1, 3, 4, 5, 6, 8, 9]
[[ 290    2 1265   39    9    7  162    4   72 5053]
 [   8 4293    7    7   10   11    7 3526    8    0]
 [ 323  423  246  216 4863   78  147  436  201   57]
 [4581  449  461  193  216   45   31   58 1083   24]
 [   0  178  288 3728   29 2173  168  234   17    9]
 [2129  155 1812  432    7  215   67  280 1156   60]
 [  38  190 2068   67   53    4 4326   45   14   71]
 [   6  372   12 2094   53 4399    4  314   18   21]
 [1212  335  292  208   53  193   51  330 4115   36]
 [  87  261   31 3462   19 2849   16   95   87   51]]


In [33]:
fileObject = open("kmeans_argmax.pkl", 'wb')
pkl.dump(theBiggest, fileObject)
fileObject.close()

In [ ]:
#DBSCAN