In [1]:
#Przygotowanie danych
import numpy as np
import pickle as pkl
from sklearn.metrics import confusion_matrix
from sklearn.datasets import fetch_openml
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

In [2]:
mnist = fetch_openml('mnist_784', version=1)

In [3]:
X = mnist['data']
y = mnist['target'].astype(np.uint8)

In [4]:
print(X)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel7

In [5]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Columns: 784 entries, pixel1 to pixel784
dtypes: float64(784)
memory usage: 418.7 MB


In [6]:
print(y)

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: uint8


In [7]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 70000 entries, 0 to 69999
Series name: class
Non-Null Count  Dtype
--------------  -----
70000 non-null  uint8
dtypes: uint8(1)
memory usage: 68.5 KB


In [8]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [9]:
#Zbiór uczący i testowy

In [13]:
#Posortowanie danych
y = y.sort_values()
index = y.index
X = X.reindex(index=index)

In [14]:
#losowy podział
shuffle_index = np.random.permutation(70000)
X = X.reindex(index=shuffle_index)
y = y.reindex(index=shuffle_index)

In [15]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [33]:
y_train.values

array([3, 5, 1, ..., 6, 8, 1], dtype=uint8)

In [34]:
y_test.values

array([5, 4, 9, ..., 2, 2, 7], dtype=uint8)

In [18]:
#Uczenie - jedna klasa

In [19]:
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
print(y_train_0)
print(np.unique(y_train_0))
print(len(y_train_0))

60677    False
46331    False
37232    False
53172    False
49861    False
         ...  
20819    False
14748    False
623      False
28297    False
35252    False
Name: class, Length: 56000, dtype: bool
[False  True]
56000


In [20]:
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)

SGDClassifier(random_state=42)

In [21]:
#4 - policz dokładność (accurancy)

In [22]:
scoreTrain = sgd_clf.score(X_train,y_train_0)
scoreTest = sgd_clf.score(X_test,y_test_0)

acc = list()
acc.append(scoreTrain)
acc.append(scoreTest)

print(scoreTrain, scoreTest)
fileObject = open("sgd_acc.pkl", 'wb')
pkl.dump(acc, fileObject)
fileObject.close()

0.9893928571428572 0.987


In [23]:
#4 - walidacja krzyżowa dokładności modelu

In [24]:
score = cross_val_score(sgd_clf, X_train, y_train_0,
cv=3, scoring="accuracy")

In [25]:
print(score)
fileObject = open("sgd_cva.pkl", 'wb')
pkl.dump(score, fileObject)
fileObject.close()

[0.98328601 0.98794664 0.9813029 ]


In [26]:
#Uczenie - wiele klas

In [27]:
sgd_clf.fit(X_train, y_train)

SGDClassifier(random_state=42)

In [28]:
score = cross_val_score(sgd_clf, X_train, y_train,
cv=3, scoring="accuracy")
print(score)

[0.88776986 0.85927037 0.88492446]


In [29]:
y_train_pred = cross_val_predict(sgd_clf, X_train, y_train, cv=3)

In [30]:
conf_mx = confusion_matrix(y_train, y_train_pred)
print(conf_mx)

[[5365    0   26   20   11   37   33    5   51   25]
 [   1 5969   50   53    5   28    9    8   99   32]
 [  56   51 4654  274   76   46   97   82  165   39]
 [  34   10  100 5113   13  168   16   45  121   96]
 [  18   17   39   17 4795   23   63   44   98  389]
 [  71   16   24  439   86 3996  107   21  214  121]
 [  64   20   37   13   27  134 5177    7   62    6]
 [  20   16   75  124   75   15    9 5008   40  414]
 [  50   81   90  485   33  249   38   27 4122  234]
 [  34   20   13  105  181   42    5  177   59 4931]]


In [31]:
print(type(conf_mx))

<class 'numpy.ndarray'>


In [32]:
fileObject = open("sgd_cmx.pkl", 'wb')
pkl.dump(conf_mx, fileObject)
fileObject.close()