In [1]:
from sklearn.datasets import fetch_openml 
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False) 
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [2]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
silhouette_scores = []
kmeans_10 = None

for i in range(8,13):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit_predict(X)
    if i == 10:
        kmeans_10 = kmeans
    silhouette_scores.append(silhouette_score(X, kmeans.labels_))

In [3]:
print(silhouette_scores)

[0.07338401965925966, 0.05683381826333592, 0.05869201052848778, 0.05836351154790604, 0.05894738457992754]


In [4]:
import pickle as pkl
fileObject = open("kmeans_sil.pkl", 'wb')
pkl.dump(silhouette_scores, fileObject)
fileObject.close()

In [5]:
from sklearn.metrics import confusion_matrix
conMatrix = confusion_matrix(y, kmeans_10.predict(X))
theBiggest = set()
for row in conMatrix:
    theBiggest.add(np.argmax(row))
theBiggest = list(theBiggest)
theBiggest.sort()
print(theBiggest)
print(conMatrix)

9
1
4
0
3
0
6
5
8
3
[0, 1, 3, 4, 5, 6, 8, 9]
[[ 290    2 1265   39    9    7  162    4   72 5053]
 [   8 4293    7    7   10   11    7 3526    8    0]
 [ 323  423  246  216 4863   78  147  436  201   57]
 [4581  449  461  193  216   45   31   58 1083   24]
 [   0  178  288 3728   29 2173  168  234   17    9]
 [2129  155 1812  432    7  215   67  280 1156   60]
 [  38  190 2068   67   53    4 4326   45   14   71]
 [   6  372   12 2094   53 4399    4  314   18   21]
 [1212  335  292  208   53  193   51  330 4115   36]
 [  87  261   31 3462   19 2849   16   95   87   51]]


In [6]:
fileObject = open("kmeans_argmax.pkl", 'wb')
pkl.dump(theBiggest, fileObject)
fileObject.close()

In [7]:
#DBSCAN

In [8]:
#Policz odległości dla pierwszych 300 elementów ze zbioru X
eps = set()
for i in range(300):
    #for j in range (300):
    for j in range(len(X)):
        if i!=j:
            eps.add(np.linalg.norm(X[i]-X[j]))
eps = list(eps)
eps.sort()
eps = eps [0:10]
print(eps)  

fileObject = open("dist.pkl", 'wb')
pkl.dump(eps, fileObject)
fileObject.close()

[279.26152617215286, 304.37641170103836, 317.5893575043093, 328.7658741414626, 333.4546445920344, 352.89800226127664, 355.1774204534967, 358.07401469528617, 359.64287842247063, 360.42474942767177]


In [11]:
dbscan_len = []
from sklearn.cluster import DBSCAN
s = (eps[0] + eps[1] + eps[2]) / 3
i = s
while i <= s+0.10*s:
    dbscan = DBSCAN(eps=i)
    dbscan.fit(X)
    dbscan_len.append(len(set(dbscan.labels_)))
    i += 0.04*s
    
fileObject = open("dbscan_len.pkl", 'wb')
pkl.dump(dbscan_len, fileObject)
fileObject.close()

In [12]:
print(dbscan_len)

[4, 7, 22]
